version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "14268:14268"   # HTTP collector
      - "4317:4317"     # OTLP gRPC (optional)
      - "4318:4318"     # OTLP HTTP (optional)
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    restart: unless-stopped
