apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: jaeger-collector
spec:
  selector:
    app.kubernetes.io/name: jaeger-collector
  ports:
    - name: http-collector
      port: 14268
      targetPort: 14268
      protocol: TCP
  type: ClusterIP
